name: Build Allrounder99 APK

on:
  workflow_dispatch:

jobs:
  build-apk-aab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find source zip
        run: |
          ZIP_FILE=$(ls *.zip | head -n 1)
          echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV
          echo "Using $ZIP_FILE"

      - name: Unzip app source
        run: unzip -q "$ZIP_FILE"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Android project files
        working-directory: allrounder99_flutter_app
        run: flutter create --platforms=android --org com.allrounder99 .

      - name: Get packages
        working-directory: allrounder99_flutter_app
        run: flutter pub get

      - name: Build APK
        working-directory: allrounder99_flutter_app
        run: flutter build apk --release --build-name=1.0.1 --build-number=2

      - name: Build Play Store AAB
        working-directory: allrounder99_flutter_app
        run: flutter build appbundle --release --build-name=1.0.1 --build-number=2

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Allrounder99-APK
          path: allrounder99_flutter_app/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Play Store AAB
        uses: actions/upload-artifact@v4
        with:
          name: Allrounder99-PlayStore-AAB
          path: allrounder99_flutter_app/build/app/outputs/bundle/release/app-release.aab
